openapi: 3.0.3
info:
  title: Aura Pedido API
  description: API do Microsserviço de Pedido para o Sistema de Gerenciamento de Pedidos
  version: 1.0.0
  contact:
    name: Equipe Aura
    email: equipe@aura.com.br
servers:
  - url: 'http://localhost:8002'
    description: Servidor local
tags:
  - name: orders
    description: Operações relacionadas a pedidos

paths:
  /orders:
    get:
      tags:
        - Orders
      summary: Retorna a lista de pedidos
      operationId: getOrders
      responses:
        '200':
          description: Lista de pedidos retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderResponseDTO'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/orders/new-solicitation:
    post:
      tags:
        - Orders
      summary: Cria uma nova solicitação de pedido
      operationId: createOrder
      requestBody:
        required: true
        description: Dados do pedido
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRequestDTO'
      responses:
        '200':
          description: Solicitação processada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponseDTO'
        '400':
          description: Requisição inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    OrderRequestDTO:
      type: object
      required:
        - clientId
        - orderDetails
      properties:
        clientId:
          type: string
          format: uuid
          example: '550e8400-e29b-41d4-a716-446655440000'
          description: ID do cliente
        orderDetails:
          type: string
          example: '2 pizzas de calabresa'
          description: Detalhes do pedido
        additionalNotes:
          type: string
          nullable: true
          example: 'Sem cebola'
          description: Observações adicionais

    OrderResponseDTO:
      type: object
      properties:
        orderId:
          type: string
          format: uuid
          example: '550e8400-e29b-41d4-a716-446655440000'
          description: ID do pedido
        status:
          type: string
          enum: ['FECHADO_COM_SUCESSO', 'FECHADO_SEM_CREDITO', 'FECHADO_SEM_ESTOQUE', 'ERRO']
          example: 'PENDING'
          description: Status do pedido
        createdAt:
          type: string
          format: date-time
          example: '2023-01-01T12:00:00Z'
          description: Data de criação do pedido

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: 'Invalid request'
        message:
          type: string
          example: 'Client ID is required'
        statusCode:
          type: integer
          example: 400
        timestamp:
          type: string
          format: date-time
          example: '2023-01-01T12:00:00Z'