CREATE TABLE PAYMENT
(
    ID          BIGSERIAL PRIMARY KEY,
    ORDER_ID    VARCHAR(255)   NOT NULL,
    CARD_NUMBER VARCHAR(255)   NOT NULL,
    AMOUNT      DECIMAL(19, 2) NOT NULL,
    STATUS      VARCHAR(50)    NOT NULL,
    CREATED_AT  TIMESTAMP      NOT NULL,
    UPDATED_AT  TIMESTAMP
);