CREATE TABLE STOCK
(
    ID           BIGSERIAL PRIMARY KEY,
    SKU_PRODUCT  VARCHAR(50) UNIQUE NOT NULL,
    NAME_PRODUCT VARCHAR(100),
    QUANTITY     BIGSERIAL,
    TOTAL_VALUE  DECIMAL(10, 2),
    VALUE_UNIT   DECIMAL(10, 2),
    VALUE_SALE   DECIMAL(10, 2),
    STATUS       VARCHAR(20) DEFAULT 'AVALIABLE' CHECK (STATUS IN ('AVALIABLE', 'UNAVALIABLE', 'DISCONTINUED')),
    DT_REGISTER  TIMESTAMP   DEFAULT CURRENT_TIMESTAMP
);