openapi: 3.0.3
info:
  title: Aura Pagamento API
  description: API do Microsserviço de Pagamento para o Sistema de Gerenciamento de Pagamentos
  version: 1.0.0
  contact:
    name: Equipe Aura
    email: equipe@aura.com.br
servers:
  - url: 'http://localhost:8086'
    description: Servidor local
tags:
  - name: payments
    description: Operações relacionadas a pagamentos

paths:
  /payments/process:
    post:
      tags:
        - payments
      summary: Processa um novo pagamento
      operationId: processPayment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
      responses:
        '200':
          description: Pagamento processado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '400':
          description: Requisição inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'

  /payments/{orderId}:
    get:
      tags:
        - payments
      summary: Obtém o status de um pagamento pelo ID do pedido
      operationId: getPaymentStatus
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Status do pagamento obtido com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '400':
          description: Requisição inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'

components:
  schemas:
    PaymentRequest:
      type: object
      required:
        - orderId
        - cardNumber
        - amount
      properties:
        orderId:
          type: string
          description: Identificador único do pedido
        cardNumber:
          type: string
          description: Número do cartão de crédito
        amount:
          type: number
          format: double
          description: Valor do pagamento
        customerId:
          type: string
          description: Identificador do cliente

    PaymentResponse:
      type: object
      properties:
        orderId:
          type: string
          description: Identificador único do pedido
        status:
          type: string
          enum: [PENDING, COMPLETED, FAILED, REFUNDED]
          description: Status do pagamento
        message:
          type: string
          description: Mensagem descritiva sobre o resultado do processamento
        processedAt:
          type: string
          format: date-time
          description: Data e hora do processamento