INSERT INTO PRODUCT (NAME, SKU, PRICE, DESCRIPTION)
VALUES ('Smartphone Galaxy X20', 'SMGX20-BLK', 999.99,
        'Smartphone com tela AMOLED de 6.5", 128GB de armazenamento e 8GB de RAM'),
       ('Notebook UltraBook Pro', 'ULTP-15-SLV', 2499.99,
        'Notebook ultrafino com processador i7, 16GB RAM, 512GB SSD e tela 15.6"'),
       ('Fone de Ouvido Wireless', 'HDPHN-WL-BLK', 149.99,
        'Fones com cancelamento de ruído, bluetooth 5.0 e bateria de longa duração'),
       ('Smart TV 55" LED 4K', 'TV55-4K-SMART', 1899.99,
        'TV com resolução 4K, HDR10+, sistema operacional próprio e conectividade Wi-Fi'),
       ('Câmera DSLR Profissional', 'CAM-DSLR-PRO', 1299.50, 'Câmera com 24.2MP, gravação 4K e kit com lente 18-55mm'),
       ('Tablet Premium 10"', 'TAB-10-PRO', 799.00,
        'Tablet com tela 10", processador octa-core, 6GB RAM e 128GB armazenamento'),
       ('Console de Jogos NextGen', 'GAME-NG-1TB', 2999.99,
        'Console com 1TB SSD, processador de última geração, suporte a jogos 4K'),
       ('Smartwatch Fitness', 'SWTCH-FIT-BLK', 299.50,
        'Relógio inteligente com monitor cardíaco, GPS, resistente à água e bateria de 7 dias'),
       ('Impressora Multifuncional', 'PRINT-MULT-CLR', 399.99,
        'Impressora com scanner, copiadora, Wi-Fi e impressão frente e verso automática'),
       ('Drone com Câmera HD', 'DRONE-HD-PRO', 899.00,
        'Drone com câmera HD, alcance de 5km, 30 minutos de voo e recursos de gravação automática'),
       ('Mouse Gamer RGB', 'MOUSE-GMR-RGB', 199.90, 'Mouse com iluminação RGB, 16000 DPI e 8 botões programáveis'),
       ('Teclado Gamer Mecânico', 'KEY-GMR-MECH', 349.90,
        'Teclado mecânico com switches mecânicos, retroiluminação RGB e design ergonômico'),
       ('Monitor LED 24" Full HD', 'MON-24-FHD', 799.90,
        'Monitor com resolução Full HD, tempo de resposta de 5ms e ângulo de visão de 178°'),
       ('HD SSD 1TB NVMe', 'SSD-1TB-NVME', 599.90,
        'SSD NVMe com velocidade de leitura até 3500MB/s e gravação até 3000MB/s'),
       ('Cabo HDMI Ultra HD', 'CABO-HDMI-UHD', 49.90,
        'Cabo HDMI com suporte a 4K, 60Hz e alta velocidade de transferência'),
       ('Adaptador USB-C para HDMI', 'ADAPT-USB-C-HDMI', 89.90,
        'Adaptador USB-C para HDMI com suporte a resolução 4K e plug and play'),
       ('Microfone Condensador USB', 'MIC-COND-USB', 199.00,
        'Microfone USB com qualidade profissional, ideal para gravações e transmissões ao vivo'),
       ('Caixa de Som Bluetooth Portátil', 'SPKR-BT-POR', 149.90,
        'Caixa de som portátil com bluetooth, resistência à água e bateria de longa duração'),
       ('Carregador Rápido USB-C', 'CHARGER-USB-C', 79.90,
        'Carregador rápido USB-C com potência de até 30W e compatível com diversos dispositivos'),
       ('Cabo de Rede Cat 6', 'CABO-REDE-CAT6', 29.90,
        'Cabo de rede com alta velocidade de transferência, ideal para jogos e streaming'),
       ('Suporte para Monitor Ajustável', 'SUP-MON-ADJ', 199.90,
        'Suporte para monitor com ajuste de altura, rotação e inclinação'),
       ('Mouse Pad Gamer Grande', 'PAD-GMR-LARGE', 89.90,
        'Mouse pad grande com superfície lisa, ideal para jogos e trabalho'),
       ('Teclado Sem Fio Compacto', 'KEY-WIRELESS-CMP', 129.90,
        'Teclado sem fio compacto com bateria de longa duração e design ergonômico'),
       ('Fone de Ouvido Over-Ear', 'HDPHN-OVER-BLK', 299.00,
        'Fones over-ear com som estéreo, almofadas confortáveis e bluetooth 5.0'),
       ('Monitor Gamer 24" Full HD', 'MON-G24-FHD', 899.90,
        'Monitor gamer com taxa de atualização de 144Hz, tempo de resposta de 1ms e resolução Full HD'),
       ('Monitor Gamer 27" Curvo', 'MON-G27-CURV', 1399.90,
        'Monitor curvo com taxa de atualização de 165Hz, 1ms de resposta e resolução Full HD'),
       ('Roteador Wi-Fi 6 Dual Band', 'ROUT-WF6-DB', 499.00,
        'Roteador com suporte a Wi-Fi 6, velocidade até 1800Mbps e cobertura ampliada'),
       ('Teclado Mecânico RGB', 'KEY-MECH-RGB', 349.99,
        'Teclado com switches mecânicos, iluminação RGB customizável e estrutura em alumínio'),
       ('HD Externo 2TB USB 3.0', 'HDD-EXT-2TB', 459.90,
        'HD portátil com conexão USB 3.0, design compacto e alta velocidade de transferência'),
       ('Carregador Portátil 20000mAh', 'PWR-BNK-20K', 199.90,
        'Power bank com duas saídas USB, carregamento rápido e indicador LED'),
       ('Cadeira Gamer Reclinável', 'GMR-CHAIR-BLK', 1299.00,
        'Cadeira ergonômica com encosto reclinável, apoio lombar e ajuste de altura'),
       ('Webcam Full HD com Microfone', 'WEB-HD-MIC', 259.90,
        'Webcam com resolução 1080p, microfone embutido e clip universal'),
       ('Caixa de Som Bluetooth', 'SPKR-BT-PORT', 229.90,
        'Caixa de som portátil com som estéreo, resistência à água e bateria de 10h'),
       ('Placa de Vídeo RTX 4060', 'GPU-RTX4060', 2999.99,
        'Placa gráfica com 8GB GDDR6, Ray Tracing e suporte a DLSS 3'),
       ('Estabilizador de Energia 1000VA', 'ESTAB-1000VA', 329.90,
        'Estabilizador com 6 tomadas, proteção contra surtos e tecnologia de microprocessador'),
       ('Fonte ATX 600W', 'PSU-600W', 249.90, 'Fonte com 80 Plus Bronze, cabos modulares e proteção contra sobrecarga'),
       ('Teclado Gamer RGB Mecânico', 'KEY-GMR-RGB-MECH', 399.90,
        'Teclado mecânico com retroiluminação RGB, switches mecânicos e design ergonômico'),
       ('Mouse Gamer Sem Fio', 'MOUSE-WIRELESS-GMR', 199.90,
        'Mouse gamer sem fio com sensor de alta precisão e iluminação RGB'),
       ('Câmera de Segurança Wi-Fi', 'CAM-SEC-WIFI', 299.90,
        'Câmera de segurança com visão noturna, detecção de movimento e áudio bidirecional'),
       ('Carregador Veicular USB-C', 'CAR-CHARGER-USB-C', 79.90,
        'Carregador veicular USB-C com potência de até 30W e compatível com diversos dispositivos'),
       ('Adaptador HDMI para VGA', 'ADAPT-HDMI-VGA', 49.90,
        'Adaptador HDMI para VGA com suporte a resolução Full HD e plug and play'),
       ('Hub USB 3.0 com Leitor de Cartão', 'HUB-USB3-CARDREADER', 89.90,
        'Hub USB 3.0 com leitor de cartão SD/microSD e design compacto'),
       ('Suporte para Celular Ajustável', 'SUP-CELL-ADJ', 39.90,
        'Suporte ajustável para celular com base antiderrapante e design portátil'),
       ('Cabo Lightning para USB', 'CABO-LIGHTNING-USB', 29.90,
        'Cabo Lightning com suporte a carregamento rápido e transferência de dados'),
       ('Teclado Gamer RGB Compacto', 'KEY-GMR-RGB-CMP', 299.90,
        'Teclado gamer compacto com retroiluminação RGB e switches mecânicos'),
       ('Mouse Pad Gamer RGB', 'PAD-GMR-RGB', 99.90,
        'Mouse pad gamer com iluminação RGB e superfície otimizada para jogos'),
       ('Fone de Ouvido Bluetooth', 'HDPHN-BT', 199.90,
        'Fones bluetooth com som estéreo, resistência à água e bateria de longa duração'),
       ('Cabo Auxiliar P2', 'CABO-AUX-P2', 19.90,
        'Cabo auxiliar P2 com conectores banhados a ouro e alta qualidade de som'),
       ('Teclado Mecânico Compacto', 'KEY-MECH-CMP', 299.90,
        'Teclado mecânico compacto com switches mecânicos e design ergonômico'),
       ('Mouse Gamer RGB Sem Fio', 'MOUSE-GMR-RGB-WIRELESS', 249.90,
        'Mouse gamer sem fio com iluminação RGB e sensor de alta precisão');
